name: Build Python Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Set Up Python
        uses: actions/setup-Python
        with:
          python-version: "3.12"
      
      - name: Install Build Module
        run: pip install build
      
      - name: Build Package
        run: python -m build

      - name: Upload dist artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.1.0
          files: dist/*
          